[2025-06-25 10:21:02 +0200] [277337] [INFO] Starting gunicorn 23.0.0
[2025-06-25 10:21:02 +0200] [277337] [INFO] Listening at: http://0.0.0.0:8000 (277337)
[2025-06-25 10:21:02 +0200] [277337] [INFO] Using worker: sync
[2025-06-25 10:21:02 +0200] [277343] [INFO] Booting worker with pid: 27[2025-06-25 12:01:53 +0200] [[2025-06-25 12:01:53 +0200] [277337] [INFO] Handlin[2025-06-25 12:01:54 +0200] [332091]Traceback (most recent call last):
  File "/usr/lib/python3.13/logging/__init__.py", line 1153, in emit
 [2025-06-25 12:02:14 +0200] [332091] [INFO] Worker exiting (pid: 332091)
[settings] DJANGO_ENV = local
[settings] Variables cargadas desde: /home/markmur88/api_bank_h2/.env.local
⚠️ Django apps aún no están listas. Configuración dinámica omitida.
[2025-06-25 12:02:14 +0200] [11429] [INFO] Shutting down: Master
 emit
    stream.write(msg + self.terminator)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/arbiter.py", line 241, in handle_chld
    self.reap_workers()
    ~~~~~~~~~~~~~~~~~^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/arbiter.py", line 553, in reap_workers
    self.log.error(msg)
    ~~~~~~~~~~~~~~^^^^^
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/glogging.py", line 271, in error
    self.error_log.error(msg, *args, **kwargs)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1548, in error
    self._log(ERROR, msg, args, **kwargs)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1664, in _log
    self.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1680, in handle
    self.callHandlers(record)
    ~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1736, in callHandlers
    hdlr.handle(record)
    ~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1026, in handle
    self.emit(record)
    ~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1158, in emit
    self.handleError(record)
    ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/logging/__init__.py", line 1074, in handleError
    sys.stderr.write('--- Logging error ---\n')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: reentrant call inside <_io.BufferedWriter name='<stderr>'>
Call stack:
  File "/home/markmur88/envAPP/bin/gunicorn", line 8, in <module>
    sys.exit(run())
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/wsgiapp.py", line 66, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]", prog=prog).run()
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/base.py", line 235, in run
    super().run()
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/app/base.py", line 71, in run
    Arbiter(self).run()
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/arbiter.py", line 222, in run
    self.log.info("Handling signal: %s", signame)
  File "/home/markmur88/envAPP/lib/python3.13/site-packages/gunicorn/glogging.py", line 277, in info
    self.error_log.info(msg, *args, **kwargs)
Message: 'Handling signal: %s'
Arguments: ('hup',)
[2025-06-25 12:01:56 +0200] [277337] [INFO] Hang up: Master
[2025-06-25 12:01:57 +0200] [277337] [INFO] Handling signal: term
[2025-06-25 12:01:57 +0200] [332110] [INFO] Booting worker with pid: 332110
[2025-06-25 12:02:27 +0200] [277337] [INFO] Shutting down: Master
